#!/usr/bin/env bash

# Copyright 07/06/2015 Aaron Caffrey https://github.com/wifiextender

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.


# bash bootstrap archlinux
# ./configure --prefix=$HOME/.cache
# make && make install

declare -a _bases
_bases=(
    'archlinux'
    'debian'
    'gentoo'
    'slackware'
    'rhel'
    'frugalware'
    'angstrom'
)

_printf_err() {
    printf '%s\n' "try again with: bash $0 basedistro"
    printf '%s ' "Bases: ${_bases[@]}"
}

_gen_files() {
  prog_name='dwmbar'
  prog_ver='0.8'


  # configure.ac
  configure_ac=("# This file is processed by autoconf to create a configure script
  AC_INIT(["${prog_name}"], ["${prog_ver}"])
  AC_CONFIG_AUX_DIR([temp_dir])
  AC_CONFIG_MACRO_DIR([m4])
  AM_INIT_AUTOMAKE([1.11 -Wall no-define foreign subdir-objects dist-xz no-dist-gzip std-options])

  AM_SILENT_RULES([yes])
  AC_PROG_CC_STDC
  AC_C_CONST
  AC_HEADER_STDC
  AM_PROG_CC_C_O

  # The linker flags tests in m4 dir
  TEST_X11
  TEST_ALSA

  AC_CONFIG_FILES([
  Makefile
  src/Makefile
  ])

  AC_OUTPUT

  echo
  echo 'Now type \"make\" and \"make install\" afterwards'
  echo")


  # Makefile.am
  main_makefile=('
  SUBDIRS = \
      src
  ')


  # src/Makefile.am
  src_files=(
      'main.c'
      'functions.c'
      'functions.h'
      'constants1.h'
      'constants2.h'
  )

  src_makefile=('AM_CPPFLAGS = \
      -DGIVEN_DISTRO=\"'$1'\"

  bin_PROGRAMS = \
    '${prog_name}'

  '${prog_name}'_CFLAGS = \
    -O2 -Wextra -Wall -fno-aggressive-loop-optimizations \
    -Wundef -Wwrite-strings -Wcast-align -Wstrict-overflow=5 \
    -W -Wshadow -Wconversion -Wpointer-arith -Wstrict-prototypes \
    -Wformat=2 -Wmissing-prototypes

  '${prog_name}'_LDADD = $(X_LIBS) $(ALSA_LIBS)

  '${prog_name}'_SOURCES = '${src_files[@]}'
  ')


  cat <<EOF > configure.ac
${configure_ac[@]}
EOF

  cat <<EOF > Makefile.am
${main_makefile[@]}
EOF

  cat <<EOF > src/Makefile.am
${src_makefile[@]}
EOF


  # do not remove nor edit
  autoreconf --install --force
}


[[ -z $1 ]] && _printf_err $@ || {
    [[ " ${_bases[@]} " =~ " $1 " ]] && \
        _gen_files $@ || _printf_err $@
}
