name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -name: perl set.pl debian
      run: perl set.pl debian
    -name: autoreconf
      run: autoreconf --install --force
    - name: configure
      run: ./configure --without-colors
    - name: make
      run: make
